# Generated by Django 5.1.5 on 2025-03-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
