# Generated by Django 5.1.5 on 2025-03-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_supplier_store_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_info',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
